Feat: Gitops optional for cicd
devtron-labs/devtron pull request #1861
Opened 2022-06-10 09:52 UTC by vikramdevtron

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] App workflow
- [ ] Cd pipeline create without gitops and with gitops
- [ ] CD pipeline trigger for both help type and acd type.
- [ ] CD pipeline delete both helm and acd type pipeline.
- [ ] App detail - resource tree
- [ ] App workflow - cd pipeline status

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles
* [ ] I have added all the required unit/api test cases

2022-06-10 14:48 UTC, nishant-d requested changes

2022-06-10 14:48 UTC, nishant-d commented on internal/util/ChartService.go
> +const PIPELINE_DEPLOYMENT_TYPE_ACD string = "acd"
ARGO_CD

2022-06-11 05:45 UTC, vikramdevtron commented on api/restHandler/AppListingRestHandler.go
> +func (handler *AppListingRestHandlerImpl) GetClusterConf(clusterId int) (*client.ClusterConfig, error) {
moved, completed

2022-06-11 05:46 UTC, vikramdevtron commented on api/restHandler/common/apiError.go
> +func ConvertResourceTree(resp interface{}) map[string]interface{} {
moved and renamed into helper

2022-06-11 05:46 UTC, vikramdevtron commented on internal/util/ChartService.go
> +const PIPELINE_DEPLOYMENT_TYPE_ACD string = "acd"
corrected -> small case - "argo_cd"

2022-06-11 05:46 UTC, vikramdevtron commented on pkg/app/AppService.go
> +			flag, err := impl.updateArgoPipeline(overrideRequest.AppId, pipeline.Name, envOverride, ctx)
done

2022-06-13 11:23 UTC, nishant-d approved these changes

2022-06-13 11:23 UTC, merged