chart documentation done
devtron-labs/devtron pull request #217
Opened 2021-02-01 05:53 UTC by shivani170

please review

2021-02-01 05:55 UTC, pghildiyal commented on docs/user-guide/global-configurations/chart-repo.md
> +The Global configuration provides a feature of `chart repository` in which you can add your chart repository here.
Add path to access the repository

2021-02-01 06:07 UTC, pghildiyal requested changes

2021-02-01 06:07 UTC, pghildiyal commented on docs/user-guide/global-configurations/chart-repo.md
> +Provide a `Name` to your Chart Repository. It will be added as one option in the Chart Repository drop-down inside the Chart Repository section.
User will not be able to understand as this required deep product knowledege... it should be something like - 'This name is added as prefix to the name of the chart in the listing on the helm chart section of application' and add image to show it

2021-02-01 06:07 UTC, pghildiyal commented on docs/user-guide/global-configurations/chart-repo.md
> +Provide the `URL` of your Version Controller. **For example**- github.com for Github, [https://gitlab.com](https://gitlab.com) for GitLab, etc.
what is the purpose of this version controller?

2021-02-01 06:07 UTC, pghildiyal commented on docs/user-guide/global-configurations/chart-repo.md
> +If you select Password/Auth token then you have to provide the `Access token` for the authentication of your version controller account inside the Access token box. Click on `Save` to save your chart
Access Token or Password

T capital for Auth token

2021-02-01 06:07 UTC, pghildiyal commented on docs/user-guide/global-configurations/chart-repo.md
> +You can update your saved chart repository settings at any point in time. Click on the chart repository which you want to update. Make changes and click on \`Update to save you changes.
Update to save your changes has open tick but not closing tick, instead of  '\`Update -> '`Update`'

2021-02-03 05:30 UTC, spruhapandya12 requested changes

2021-02-03 05:30 UTC, spruhapandya12 commented on docs/user-guide/global-configurations/chart-repo.md
> +This feature allows you to add more chart repositories to Devtron. Once added they will be available in the Discover section of the Chart Store.
This feature allows you to add chart repositories to Devtron. You can add as many chart repositories as you require. Once added, they will be available in the Discover section of the 'Chart Store'.

2021-02-03 07:04 UTC, shivani170 commented on docs/user-guide/global-configurations/chart-repo.md
> +This feature allows you to add more chart repositories to Devtron. Once added they will be available in the Discover section of the Chart Store.
comma or backtick

2021-02-03 07:38 UTC, spruhapandya12 requested changes

2021-02-03 07:38 UTC, spruhapandya12 commented on docs/user-guide/global-configurations/chart-repo.md
> +Here you have to provide the type of Authentication required by your version controller. We are supporting three types of authentications, you can choose any one from them.
Here, you have to provide the type of Authentication required by your version controller. We support three types of authentications. You can choose the one that suits you the best.

2021-02-03 07:38 UTC, spruhapandya12 commented on docs/user-guide/global-configurations/chart-repo.md
> +If you select `Anonymous` then you do not have to provide any username, password, and authentication token. Just click on `Save` to save your chart repository details.
If you select `Anonymous` then you do not have to provide any username, password, or authentication token. Just click on `Save` to save your chart repository details.

2021-02-03 07:38 UTC, spruhapandya12 commented on docs/user-guide/global-configurations/chart-repo.md
> +If you select Password/Auth token then you have to provide the `Access Token` for the authentication of your version controller account inside the Access token box. Click on `Save` to save your chart
If you select Password/Auth token, then you have to provide the `Access Token` for the authentication of your version controller account inside the Access token box. Click on `Save` to save your chart repository details.

2021-02-03 07:38 UTC, spruhapandya12 commented on docs/user-guide/global-configurations/chart-repo.md
> +You can update your saved chart repository settings at any point in time. Click on the chart repository which you want to update. Make changes and click on `Update` to save you changes.
You can update your saved chart repository settings at any point in time. Just click on the chart repository which you want to update, make the required changes and click on `Update` to save your changes.

2021-02-03 10:21 UTC, shivani170 commented on docs/user-guide/global-configurations/chart-repo.md
> +Provide a `Name` to your Chart Repository. This name is added as prefix to the name of the chart in the listing on the helm chart section of application.
please specify error?

2021-02-03 11:18 UTC, nishant-d approved these changes

2021-02-03 11:19 UTC, merged