fix: updated acd pipeline failure handling
devtron-labs/devtron pull request #2212
Opened 2022-08-23 14:07 UTC by kartik-579

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test case A
- [ ] Test case B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles
* [ ] I have added all the required unit/api test cases

2022-08-24 10:12 UTC, kartik-579 commented on internal/sql/repository/AppListingRepository.go
> +const Failure = "FAILURE"
move from repository to another file containing consts

2022-08-24 17:43 UTC, nishant-d requested changes

2022-08-24 17:43 UTC, nishant-d commented on internal/sql/repository/AppListingRepository.go
> +	query := "select distinct ds.app_name, status, max(ds.id) as id, app_id, env_id, ds.created_on, ds.updated_on from deployment_status ds inner join app on app.id=ds.app_id inner join environment env
filter-out data based on deployment time and status to reduce list size otherwise for large users it will create performance issue

2022-08-24 17:43 UTC, nishant-d commented on pkg/pipeline/CdHandler.go
> +			cdWfr, err = impl.cdWorkflowRepository.FindCdWorkflowRunnerByEnvironmentIdAndRunnerType(deploymentStatus.AppId, deploymentStatus.EnvId, bean.CD_WORKFLOW_TYPE_DEPLOY)
use bulk db operations here

2022-08-24 17:43 UTC, nishant-d commented on pkg/pipeline/CdHandler.go
> +		if impl.isDeploymentFailed(deploymentStatus, timeForDegradation) {
apply this filter on db

2022-08-24 17:43 UTC, nishant-d commented on pkg/pipeline/CdHandler.go
> +			acdToken, err := impl.argoUserService.GetLatestDevtronArgoCdUserToken()
extract argo interaction out

2022-08-29 13:50 UTC, nishant-d approved these changes

2022-08-29 13:51 UTC, merged