Gitops acd integration
devtron-labs/devtron pull request #2257
Opened 2022-08-31 06:43 UTC by manish-agrawal-ai

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test case A
- [ ] Test case B

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles
* [ ] I have added all the required unit/api test cases

2022-09-02 11:45 UTC, manish-agrawal-ai commented on pkg/app/AppService.go
> +	acdToken, err := impl.argoUserService.GetLatestDevtronArgoCdUserToken("EMPTY-TOKEN")
send empty.

2022-09-02 11:47 UTC, manish-agrawal-ai commented on pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
> +	acdToken, err := impl.argoUserService.GetLatestDevtronArgoCdUserToken("EMPTY-TOKEN")
send empty

2022-09-02 11:52 UTC, manish-agrawal-ai commented on pkg/pipeline/CdHandler.go
> +	acdToken, err := impl.argoUserService.GetLatestDevtronArgoCdUserToken("EMPTY-TOKEN")
EMPTY-TOKEN

2022-09-02 11:52 UTC, manish-agrawal-ai commented on pkg/pipeline/WorkflowDagExecutor.go
> +	acdToken, err := impl.argoUserService.GetLatestDevtronArgoCdUserToken("EMPTY-TOKEN")
EMPTY-TOKEN

2022-09-02 11:53 UTC, manish-agrawal-ai commented on pkg/util/TokenCache.go
> +	/*if cfg.ACDPassword == "" {
please add comment

2022-09-02 11:55 UTC, manish-agrawal-ai reviewed
check comment

2022-09-03 12:09 UTC, nishant-d requested changes

2022-09-03 12:09 UTC, nishant-d commented on util/argo/ArgoUserService.go
> +		//TODO FIX - CHECK INTEGRATION AVAILABLE OR NOT
do we need some impl here ?

2022-09-04 07:34 UTC, nishant-d submitted a review, later dismissed

2022-09-04 08:35 UTC, nishant-d approved these changes

2022-09-04 08:51 UTC, merged