fixes in gitaccount
devtron-labs/devtron pull request #263
Opened 2021-02-09 09:39 UTC by shivani170

2021-02-09 12:04 UTC, nishant-d requested changes

2021-02-09 12:04 UTC, nishant-d commented on docs/user-guide/global-configurations/chart-repo.md
> +You can enable and disable your chart repository setting. If you enable it, then you will be able to see that enabled chart in `Discover` section of `Chart Store`.
please add hyperlink

2021-02-10 07:59 UTC, shivani170 commented on docs/user-guide/global-configurations/chart-repo.md
> +You can enable and disable your chart repository setting. If you enable it, then you will be able to see that enabled chart in `Discover` section of `Chart Store`.
docs hyperlink?

2021-02-19 11:37 UTC, nishant-d approved these changes

2021-02-19 11:37 UTC, merged