Fix: cd setting manager reload
devtron-labs/devtron pull request #2702
Opened 2022-11-29 08:24 UTC by vikramdevtron

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2022-11-30 14:32 UTC, nishant-d requested changes

2022-11-30 14:32 UTC, nishant-d commented on client/argocdServer/Connection.go
>  		log.Fatal(err)
avoid logging fatal

2022-12-02 08:03 UTC, vikramdevtron commented on client/argocdServer/Connection.go
>  		log.Fatal(err)
done

2022-12-16 07:52 UTC, kartik-579 submitted a review, later dismissed

2022-12-16 08:37 UTC, nishant-d submitted a review, later dismissed

2022-12-19 05:46 UTC, kartik-579 approved these changes

2022-12-19 05:47 UTC, merged