fix: helm app proxy chart auto fix
devtron-labs/devtron pull request #2754
Opened 2022-12-12 06:07 UTC by vikramdevtron

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2022-12-13 12:52 UTC, kartik-579 commented on pkg/appStore/deployment/service/AppStoreDeploymentService.go
> +					statusError, ok := err.(*github.ErrorResponse)
check errors for all gitOps providers

2022-12-15 13:19 UTC, kartik-579 requested changes

2022-12-15 13:19 UTC, kartik-579 commented on pkg/appStore/deployment/service/AppStoreDeploymentService.go
> +						installAppVersionRequest, err = impl.appStoreDeploymentArgoCdService.OnUpdateRepoInInstalledApp(ctx, installAppVersionRequest)
please handle error

2022-12-15 13:19 UTC, kartik-579 commented on pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
> +			installAppVersionRequest, err = impl.OnUpdateRepoInInstalledApp(ctx, installAppVersionRequest)
please handle error

2022-12-15 13:19 UTC, kartik-579 commented on pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
> +		if errorResponse, ok := err.(azuredevops.WrappedError); ok && *errorResponse.StatusCode == http.StatusNotFound {
azure sometimes also sends pointe to this wrapped error. please handle that case too.

2022-12-15 13:21 UTC, vikramdevtron commented on pkg/appStore/deployment/service/AppStoreDeploymentService.go
> +						installAppVersionRequest, err = impl.appStoreDeploymentArgoCdService.OnUpdateRepoInInstalledApp(ctx, installAppVersionRequest)
already handled, not required

2022-12-15 13:22 UTC, vikramdevtron commented on pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
> +			installAppVersionRequest, err = impl.OnUpdateRepoInInstalledApp(ctx, installAppVersionRequest)
already handled, not required

2022-12-15 13:27 UTC, kartik-579 submitted a review, later dismissed

2022-12-16 07:21 UTC, kartik-579 approved these changes

2022-12-16 12:24 UTC, merged