wip: added apis for node-[delete,cordon,drain]
devtron-labs/devtron pull request #2805
Opened 2022-12-28 14:21 UTC by kartik-579

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2022-12-29 14:24 UTC, nishant-d requested changes

2022-12-30 11:13 UTC, kartik-579 commented on util/k8s/k8sCapacityService.go
> +	k8sClientSet, err := kubernetes.NewForConfig(restConfig)
using this same client set for further use in the service

2022-12-30 11:16 UTC, kartik-579 commented on util/k8s/k8sCapacityService.go
> +	k8sClientSet, err := kubernetes.NewForConfig(restConfig)
we cordon node first and then deleteOrEvict pods. For DeleteNode we exclusively delete the node.

2023-01-02 05:24 UTC, nishant-d approved these changes

2023-01-02 05:25 UTC, merged