feat: added description field for environment
devtron-labs/devtron pull request #3020
Opened 2023-02-21 20:54 UTC by mayank-devtron

# Description

Added Description field for environment 
Fixes #3005 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-02-27 16:56 UTC, prakash100198 requested changes

2023-02-27 16:56 UTC, prakash100198 commented on pkg/cluster/EnvironmentService.go
> +	Description           string `json:"description" validate:"max=50"`
add omitempty here and in all structs, incase description is empty.

2023-02-27 16:57 UTC, prakash100198 commented on pkg/cluster/EnvironmentService.go
> +	Description           string `json:"description" validate:"max=50"`
also resolve merge conflicts

2023-02-27 17:37 UTC, prakash100198 submitted a review, later dismissed

2023-02-27 17:37 UTC, prakash100198 commented on pkg/cluster/EnvironmentService.go
> +	Description           string `json:"description" validate:"max=50"`
resolve merge conflicts

2023-04-03 14:19 UTC, iamayushm approved these changes

2023-04-06 06:47 UTC, iamayushm submitted a review, later dismissed

2023-04-12 14:55 UTC, iamayushm approved these changes

2023-04-13 08:31 UTC, vikramdevtron approved these changes

2023-04-13 10:19 UTC, merged