Gitop Doc
devtron-labs/devtron pull request #320
Opened 2021-02-25 15:25 UTC by shivani170

close https://github.com/devtron-labs/devtron/issues/307

2021-02-25 16:23 UTC, nishant-d requested changes

2021-02-25 16:23 UTC, nishant-d commented on docs/user-guide/global-configurations/gitops.md
> +What permissions are required for the gitop organization id?
permission required for `Github organization` and `Gitlab group` might be diff, please specify them

2021-03-02 12:57 UTC, rashmirai21 approved these changes

2021-03-02 14:06 UTC, nishant-d approved these changes

2021-03-02 14:06 UTC, merged