fix: Argocd rbac policy enforcement for kubelink APIs
devtron-labs/devtron pull request #3200
Opened 2023-03-28 15:07 UTC by Ash-exp

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-05-17 09:12 UTC, prakash100198 requested changes

2023-05-21 19:39 UTC, Ash-exp commented on util/k8s/k8sApplicationService.go
> +	/*sinceSeconds, err := strconv.Atoi(v.Get("sinceSeconds"))
this was already there prior my development. Should I remove !!

2023-05-21 19:41 UTC, Ash-exp commented on util/k8s/k8sApplicationService.go
> +		if err != nil || appType < DevtronAppType || appType > HelmAppType {
Implemented 👍

2023-06-21 11:17 UTC, prakash100198 submitted a review, later dismissed

2023-06-21 14:24 UTC, iamayushm approved these changes

2023-06-21 14:28 UTC, merged