Fix for source type be
devtron-labs/devtron pull request #3259
Opened 2023-04-10 05:17 UTC by Aravind-2023

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-04-11 07:44 UTC, kartik-579 requested changes

2023-04-11 07:44 UTC, kartik-579 commented on internal/sql/repository/pipelineConfig/CiPipelineMaterial.go
> +		err := tx.Update(material)
go-pg supports bulk update, use that instead of iterating through loop

2023-04-11 07:44 UTC, kartik-579 commented on internal/sql/repository/pipelineConfig/CiPipelineMaterial.go
> +		err := tx.Update(material)
with this change we should also rename the method to something like UpdateInBulk, BulkUpdate etc. to make this method generic and less confusing for others to use

2023-04-11 07:44 UTC, kartik-579 commented on pkg/pipeline/CiCdPipelineOrchestrator.go
> -			pipelineMaterial.CreatedBy = createByMap[material.GitMaterialId]
any reason for removing this line? also we should update values of UpdatedOn, UpdatedBy to have correct audit in case needed for some debugging

2023-05-02 12:37 UTC, vikramdevtron approved these changes

2023-05-03 09:53 UTC, kartik-579 approved these changes

2023-05-03 09:53 UTC, merged