Build context
devtron-labs/devtron pull request #3329
Opened 2023-05-02 05:27 UTC by gireesh-devtron

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-05-11 07:08 UTC, kartik-579 requested changes

2023-05-11 07:08 UTC, kartik-579 commented on pkg/pipeline/CiService.go
> +		impl.Logger.Errorw("error occurred while getting checkout path from git material", "gitmaterial-id", ciBuildConfigBean.BuildContextGitMaterialId, "error", err)
use camelcase got gitmaterial-id

2023-05-11 07:08 UTC, kartik-579 commented on pkg/pipeline/CiTemplateService.go
> +		ciBuildConfigBean, err = bean.OverrideCiBuildConfig(templateOverride.DockerfilePath, "", "", "", "", ".", nil)
use const for "."

2023-05-11 09:59 UTC, kartik-579 approved these changes

2023-05-11 10:43 UTC, gireesh-devtron commented on api/appbean/AppDetail.go
> +	BuildContext           string            `json:"buildContext"`
done

2023-05-11 10:43 UTC, gireesh-devtron commented on pkg/pipeline/CiTemplateService.go
> +		ciBuildConfigBean, err = bean.OverrideCiBuildConfig(templateOverride.DockerfilePath, "", "", "", "", ".", nil)
done

2023-05-12 13:39 UTC, kartik-579 approved these changes

2023-05-12 13:44 UTC, kartik-579 approved these changes

2023-05-12 13:46 UTC, merged