enhancement: made revision history limit configurable for helm upgrade
devtron-labs/devtron pull request #3353
Opened 2023-05-08 11:32 UTC by kartik-579

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-05-08 13:06 UTC, nishant-d requested changes

2023-05-08 13:06 UTC, nishant-d commented on api/helm-app/HelmAppService.go
> +	ApiCallerDevtronApp      ApiCallerAppType = "devtron-app"
please use consistent naming conventions

2023-05-08 13:21 UTC, kartik-579 commented on api/helm-app/HelmAppService.go
> +	ApiCallerDevtronApp      ApiCallerAppType = "devtron-app"
updated

2023-05-09 05:25 UTC, nishant-d approved these changes

2023-05-09 05:27 UTC, merged