chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
devtron-labs/devtron pull request #3355
Opened 2023-05-08 15:56 UTC by Juneezee

# Description

The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.

The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

```
$ make build
rm -f devtron
wire
Warning: /home/jun/Desktop/github/devtron/internal/util/MergeUtil.go:29:6: using struct literal to inject github.com/devtron-labs/devtron/internal/util.MergeUtil is deprecated and will be removed in the next release; use wire.Struct instead, see https://godoc.org/github.com/google/wire#Struct for more information.
wire: github.com/devtron-labs/devtron: wrote /home/jun/Desktop/github/waiting-for-merge/devtron/wire_gen.go
go test ./pkg/pipeline
ok  	github.com/devtron-labs/devtron/pkg/pipeline	0.051s
echo 'test cases ran successfully'
test cases ran successfully
GOOS=linux go build -o devtron \
		-ldflags="-X 'github.com/devtron-labs/devtron/util.GitCommit=ec9f262' \
		-X 'github.com/devtron-labs/devtron/util.BuildTime=2023-05-08T15:55:10Z' \
		-X 'github.com/devtron-labs/devtron/util.ServerMode=FULL'"
```

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-05-10 05:08 UTC, Juneezee commented
cc @kartik-579 @pawan-59 @kripanshdevtron @vikramdevtron

2023-05-10 05:29 UTC, kartik-579 commented
@Juneezee thanks for pointing this out, we will plan this in our upcoming sprints. You can track this ticket for the progress.

2023-05-24 09:06 UTC, Juneezee commented
friendly ping @nishant-d @pawan-mehta-dt

2023-06-14 10:12 UTC, Juneezee commented
Hi @kartik-579, I just wanted to follow up on the pull request I submitted a while ago. I understand you mentioned that you would review it, and I appreciate your time. If you happen to have some free time now or in the near future, I would be grateful if you could review the PR. Thank you for your attention, and please let me know if there's anything else I can provide or assist with.

2023-06-19 07:38 UTC, kartik-579 requested changes

2023-06-19 07:38 UTC, kartik-579 commented on pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
> +	"sigs.k8s.io/yaml"
unused import, please remove

2023-06-19 07:45 UTC, kartik-579 commented
Hi @Juneezee, sorry for the delay. I have made one comment, please made the required changes and let me know so that i can check running the application once for sanity checks. Also, building the application after the changes is recommended to avoid such cases.

2023-06-19 08:04 UTC, kartik-579 commented
@Juneezee thanks for the quick changes. The PR looks good to me, will run it through sanity checks and then we can move ahead with the merge. Please allow me some more time.

2023-06-20 12:31 UTC, kartik-579 approved these changes

2023-06-20 13:29 UTC, merged