docs: container lifecycle
devtron-labs/devtron pull request #3623
Opened 2023-07-12 12:19 UTC by Shubham9t9

# Description

2023-08-07 08:21 UTC, ashokdevtron requested changes

2023-08-07 08:21 UTC, ashokdevtron commented on docs/user-guide/creating-application/deployment-template/deployment.md
> +| `httpsGet` | Sends an HTTP GET request to a specific endpoint on the Container. |
| `httpsGet` | Sends an HTTP GET request to a specific endpoint on the container. |

2023-08-07 08:21 UTC, ashokdevtron commented on docs/user-guide/creating-application/deployment-template/deployment.md
> +| `exec` | Executes a specific command, such as pre-stop.sh, inside the cgroups and namespaces of the Container. |
| `exec` | Executes a specific command, such as pre-stop.sh, inside the cgroups and namespaces of the container. |

2023-08-07 08:21 UTC, ashokdevtron commented on docs/user-guide/creating-application/deployment-template/deployment.md
> +| `exec` | Executes a specific command, such as pre-stop.sh, inside the cgroups and namespaces of the Container. |
Please remove the full-stop after each one-liner description

2023-08-17 17:54 UTC, prakarsh-dt approved these changes

2023-08-17 17:55 UTC, merged