doc: mandatory tags feature
devtron-labs/devtron pull request #3630
Opened 2023-07-13 12:02 UTC by Shubham9t9

# Description

2023-07-13 13:06 UTC, muksUX reviewed
Name of the feature is "Tag Policy" instead of "Mandatory tags"

2023-08-07 08:08 UTC, ashokdevtron requested changes

2023-08-07 08:08 UTC, ashokdevtron commented on docs/user-guide/global-configurations/tags-policy.md
> +Within the Add Tag section, you will find two options for tags:
Within the `Add Tag` section, you will find two options for tags:

2023-08-07 08:08 UTC, ashokdevtron commented on docs/user-guide/global-configurations/tags-policy.md
> +* **Suggested tags:** These tags appear as suggestions when adding tags to applications.
**Suggested tags**:

(colon shouldn't be bold)

2023-08-07 08:08 UTC, ashokdevtron commented on docs/user-guide/global-configurations/tags-policy.md
> +* **Mandatory tags:** These tags are required for applications within the selected project.
**Mandatory tags**:

(colon shouldn't be bold)

2023-08-07 08:08 UTC, ashokdevtron commented on docs/user-guide/global-configurations/tags-policy.md
> +3. Next, choose the project(s) for which you want to create mandatory tags. You can select multiple projects at once.
Next, choose the project(s) for which you want to create mandatory tags. You can select multiple projects at once (if required).

2023-08-17 17:57 UTC, prakarsh-dt approved these changes

2023-08-17 17:59 UTC, merged