fix: prevented chart updation when its in use
devtron-labs/devtron pull request #3755
Opened 2023-08-11 10:32 UTC by ashishdevtron

# Description
Chart repo which is used to deploy helm app can be updated through postman, which should not happen.

Fixes #3455 

## How Has This Been Tested?

- [x] Tested locally

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

```release-note

```

2023-08-11 11:18 UTC, kartik-579 requested changes

2023-08-11 11:18 UTC, kartik-579 commented on pkg/chartRepo/repository/ChartRepoRepository.go
> +		" Group by chart_repo.id;"
can remove this

2023-08-11 11:18 UTC, kartik-579 commented on pkg/chartRepo/repository/ChartRepoRepository.go
> +		" (select aps.chart_repo_id as cr_id ,ia.id as ia_id from installed_app_versions iav" +
we can only make this work by only executing the subquery and putting the id where clause there only

2023-08-11 11:18 UTC, kartik-579 commented on api/chartRepo/ChartRepositoryRestHandler.go
> +		if activeDeployment > 0 {
we can move this to service layer only to avoid logic in handler

2023-08-11 11:18 UTC, kartik-579 commented on pkg/chartRepo/ChartRepositoryService.go
> +func (impl *ChartRepositoryServiceImpl) CheckDeploymentCount(request *ChartRepoDto) (int, error) {
maybe we can rename this to ValidateDeploymentCount or something similar

2023-08-14 05:28 UTC, kartik-579 requested changes

2023-08-14 05:28 UTC, kartik-579 commented on pkg/chartRepo/repository/ChartRepoRepository.go
> +		" where ia.active=true and iav.active=true and aps.chart_repo_id = " + strconv.Itoa(chartId) +
let's extract the input parameters out for better debuggability

2023-08-14 05:50 UTC, kartik-579 approved these changes

2023-08-22 08:41 UTC, merged

2023-08-22 11:44 UTC, nishant-d commented on api/chartRepo/ChartRepositoryRestHandler.go
> +	err = handler.chartRepositoryService.ValidateDeploymentCount(request)
we can put this validation after RBAC