feat: Maintaining audit logs
devtron-labs/devtron pull request #3763
Opened 2023-08-16 00:40 UTC by dhananjay0601

# Description

Maintaining Audit log for each API call so that it would significantly elevate its functionality and security.

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have performed a self-review of my own code.
* [X] I have commented my code, particularly in hard-to-understand areas.
* [X] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-08-16 12:10 UTC, vikramdevtron commented on api/logger/loggerService.go
> +	log.Println(action)
use logger to write logs in single row

2023-08-22 11:25 UTC, nishant-d requested changes

2023-08-22 11:25 UTC, nishant-d commented on api/dashboardEvent/DashboardTelemetryRouter.go
> +import (
unused import

2023-08-22 11:25 UTC, nishant-d commented on api/logger/logger.go
> +		userId, userType, err := impl.userService.GetUserByToken(r.Context(), token)
log email instead of userID, its a db call.

2023-08-22 11:25 UTC, nishant-d commented on api/logger/logger.go
> +		requestPayload := string(body)
avoid string conversion from performance POV

2023-08-22 11:25 UTC, nishant-d commented on api/logger/logger.go
> +			log.Printf("error reading request body")
add some identifier here

2023-08-22 11:25 UTC, nishant-d commented on api/logger/logger.go
> +func (impl LoggingMiddlewareImpl) LoggingMiddleware(next http.Handler) http.Handler {
make this function super efficient.

2023-08-25 13:09 UTC, vikramdevtron approved these changes

2023-08-29 11:04 UTC, vikramdevtron submitted a review, later dismissed

2023-08-29 11:12 UTC, vikramdevtron approved these changes

2023-09-01 08:13 UTC, nishant-d approved these changes

2023-09-01 08:13 UTC, merged