fix: duplicate role-group-fix
devtron-labs/devtron pull request #3774
Opened 2023-08-16 12:55 UTC by Shivam-nagar23

# Description

Fixes #3772 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [x] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-08-16 13:31 UTC, kartik-579 requested changes

2023-08-16 13:31 UTC, kartik-579 commented on pkg/user/repository/RoleGroupRepository.go
> +	err := impl.dbConnection.Model(&model).Where("casbin_name = ?", name).Where("active = ?", true).Order("updated_on desc").Select()
what is the need of ordering? if there can be multiple rows in output use limit with this or use slice model

2023-08-16 13:31 UTC, kartik-579 commented on pkg/user/RoleGroupService.go
> +		_, err := impl.roleGroupRepository.GetRoleGroupByCasbinName(object)
are we only using this for checking if entry exists or not? if yes then we should use exists clause since this is confusing. Also, add comments

2023-08-16 13:43 UTC, kartik-579 requested changes

2023-08-16 13:43 UTC, kartik-579 commented on pkg/user/RoleGroupService.go
>  			impl.logger.Errorw("role group already present", "err", err)
add roleGroup name for debugging

2023-08-16 13:58 UTC, kartik-579 approved these changes

2023-08-22 09:05 UTC, prakarsh-dt commented
@Shivam-nagar23 @kartik-579 @vikramdevtron What is the blocker here? Why are we not merging this?

2023-08-22 09:39 UTC, merged