doc: Glossary of jargonish terms for layman in the context of Devtron
devtron-labs/devtron pull request #3820
Opened 2023-08-23 13:34 UTC by ashokdevtron

2023-08-23 17:21 UTC, abhibhaw requested changes

2023-08-23 17:21 UTC, abhibhaw commented on docs/reference/glossary.md
> +    It’s a single entry point (an all-in-one YAML file) for you to enter the values, so that when the application is deployed the filled values go to the respective template files (YAML), and accordi
Na this description too is not appropriate

2023-08-23 17:21 UTC, abhibhaw commented on docs/reference/glossary.md
> +    It’s a single entry point (an all-in-one YAML file) for you to enter the values, so that when the application is deployed the filled values go to the respective template files (YAML), and accordi
And also we need to define Deployment Template before base Deployment Template?

2023-08-23 17:21 UTC, abhibhaw commented on docs/reference/glossary.md
> +    The set of files and directories used as input when building a Docker container image using a Dockerfile. Specify the set of files to be built by referring to a specific subdirectory, relative to
This too is incorrect we don't need a set of files as an input. Let's say for building a docker image: we require a dockerfile and context. Dockerfile contains the instructions to build. Context is the path where the build process may refer for files required for build

2023-09-08 14:51 UTC, abhibhaw requested changes

2023-09-14 03:22 UTC, Abhinav-26 approved these changes
Looks good to me.

2023-09-14 03:22 UTC, Abhinav-26 commented on docs/reference/glossary.md
> +The containerization of your source code followed by its deployment is totally configurable if you create a Devtron App. Custom apps deployed on Kubernetes cluster using the CI/CD feature of Devtron
This definition is good but looks a bit confusion?? Can we have something like,

Devtron Apps are the micro-services deployed with Kubernetes-native CI/CD with Devtron.

2023-09-14 20:40 UTC, abhibhaw approved these changes
LGTM. Thanks @ashokdevtron 🎉 🎉 Approving this but please don't merge I guess devops team has some ongoing release in progress.

2023-09-15 10:27 UTC, merged