docs: Ephemeral Container Doc
devtron-labs/devtron pull request #3912
Opened 2023-09-14 09:45 UTC by ashokdevtron

Doc: Launching ephemeral containers

2023-09-18 08:44 UTC, gireesh-devtron approved these changes
LGTM

2023-09-18 09:20 UTC, abhibhaw requested changes

2023-09-18 09:20 UTC, abhibhaw commented on docs/user-guide/app-details/ephemeral-containers.md
> +Ephemeral container is a temporary disposable tool that helps you fix issues in your application containers. It provides a gateway (terminal) to perform process-level and OS-level debugging, without
Definition is kinda incorrect / not clear. Please check the [official docs](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/), you can pick a few points from uses and what is section

2023-09-18 09:20 UTC, abhibhaw commented on docs/user-guide/app-details/ephemeral-containers.md
> +![Figure 1b: Removing Ephemeral Container from Resource Browser](https://devtron-public-asset.s3.us-east-2.amazonaws.com/images/debugging-deployment-and-monitoring/delete-ec-2.jpg)
Kind of same type screenshots, you can remove one, better add screenshots for other step. Possible screenshots could be:

1. How to launch
2. Basic view 
3. Advance view
4. Delete container (Already Added)

Also try to reduce repeatibility in steps if possible, few points can be clubbed from Above different ways to access

2023-09-23 15:00 UTC, abhibhaw approved these changes
LGTM 🎉 🎉 Thanks @ashokdevtron

2023-09-25 04:56 UTC, merged