docs: Scoped Variables Draft + Other Fixes (Ephemeral Doc Alignment)
devtron-labs/devtron pull request #3982
Opened 2023-09-28 13:47 UTC by ashokdevtron

doc: Contains documentation of Scoped Variables feature (Phase 1)

2023-10-05 17:10 UTC, abhibhaw requested changes

2023-10-05 17:10 UTC, abhibhaw commented on docs/user-guide/global-configurations/scoped-variables.md
> +**Option 2**: Reupload the updated YAML file
A message that this will replace the variable file, so if any varaible existed before and not in latest one will be deleted / lost

2023-10-05 17:10 UTC, abhibhaw commented on docs/user-guide/global-configurations/scoped-variables.md
> +### Order of Precedence
Maybe an example may be helpful with the below description

2023-11-06 10:54 UTC, prakarsh-dt approved these changes

2023-11-06 10:54 UTC, merged