fix: cd artifacts api
devtron-labs/devtron pull request #4064
Opened 2023-10-11 08:41 UTC by iamayushm

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-10-11 08:57 UTC, kartik-579 requested changes

2023-10-11 08:57 UTC, kartik-579 commented on pkg/pipeline/BuildPipelineConfigService.go
> +		pipelineStage, err := impl.pipelineStageRepository.GetCdStageByCdPipelineIdAndStageType(pipeline.Id, repository3.PIPELINE_STAGE_TYPE_PRE_CD)
do the same thing if parent is POST_CD, needs to be updated in RetrieveParentDetails

2023-10-11 10:45 UTC, kartik-579 requested changes

2023-10-11 10:45 UTC, kartik-579 commented on pkg/pipeline/BuildPipelineConfigService.go
> +		if pipelinePreStage != nil || len(pipeline.PreStageConfig) > 0 {
GetCdStageByCdPipelineIdAndStageType will always give  pipelinePreStage as not nill. Need to add check for pipelinePreStage.Id > 0 to be completely sure.

2023-10-11 10:45 UTC, kartik-579 commented on pkg/pipeline/DeploymentPipelineConfigService.go
> +		if len(parentPipeline.PostStageConfig) > 0 || parentPostStage != nil {
id check here as well

2023-10-11 11:09 UTC, kartik-579 submitted a review, later dismissed

2023-10-16 07:59 UTC, vikramdevtron approved these changes

2023-10-16 08:06 UTC, merged