enhancement: normal Refresh after triggering gitops deployment to avoid sync delay in argo
devtron-labs/devtron pull request #4066
Opened 2023-10-11 09:52 UTC by Shivam-nagar23

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [x] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-10-12 08:06 UTC, kartik-579 requested changes

2023-10-12 08:06 UTC, kartik-579 commented on client/argocdServer/ArgoClientWrapperService.go
> +	impl.logger.Debugw("trying to normal refresh application through get ")
add argoAppName

2023-10-12 08:06 UTC, kartik-579 commented on pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
> +// This is being done as in ea mode wire argocd service is being binded to helmServiceImpl due to which we are restricted to implement this here.
add TODO that this needs to be refactored in separate story

2023-10-12 08:06 UTC, kartik-579 commented on pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
> +	return nil
return err that this is not implemented

2023-10-17 12:40 UTC, vikramdevtron approved these changes

2023-10-18 05:27 UTC, kartik-579 approved these changes

2023-10-18 06:14 UTC, merged