fix: [Prod]Git account breaking whenever opening an existing account git repo.
devtron-labs/devtron pull request #4117
Opened 2023-10-18 10:58 UTC by ashishdevtron

# Description

Fixes # [https://dev.azure.com/DevtronLabs/Devtron/_workitems/edit/6200](url)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-10-19 12:51 UTC, kartik-579 requested changes

2023-10-19 12:51 UTC, kartik-579 commented on pkg/pipeline/GitRegistryConfig.go
> +		impl.logger.Errorw("error in fetching disabled git providers", "err", err)
add providerId in log

2023-10-19 12:51 UTC, kartik-579 commented on api/restHandler/app/AutoCompleteRestHandler.go
> +		handler.Logger.Errorw("service err, DisabledGitListAutocomplete", "err", err, "appId", appId)
add providerId

2023-10-19 13:15 UTC, kartik-579 submitted a review, later dismissed

2024-06-10 10:13 UTC, vikramdevtron commented
Not required anymore

2024-06-10 10:13 UTC, closed without merging