fix:  Unable to abort pre-cd and post-cd workflow
devtron-labs/devtron pull request #4121
Opened 2023-10-18 13:57 UTC by Ashish-devtron

# Description

Fixes #4116 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-10-18 16:10 UTC, subhashish-devtron submitted a review, later dismissed

2023-10-19 01:20 UTC, kripanshdevtron approved these changes

2023-10-19 01:21 UTC, kripanshdevtron requested changes

2023-10-19 01:21 UTC, kripanshdevtron commented on pkg/pipeline/CdHandler.go
> +	restConfig                             *rest.Config
We should not do this.

2023-10-19 06:05 UTC, kripanshdevtron approved these changes

2023-10-19 10:32 UTC, merged