docs: Added Exclude Git Files section in Existing Doc
devtron-labs/devtron pull request #4136
Opened 2023-10-19 14:49 UTC by ashokdevtron

2023-10-20 05:57 UTC, abhibhaw requested changes
We can include how to see excluded commit and its screenshot

2023-10-20 13:18 UTC, ashokdevtron commented
> We can include how to see excluded commit and its screenshot

Done

2023-10-24 03:08 UTC, uxarya-d approved these changes

2023-10-24 03:14 UTC, abhibhaw approved these changes

2023-10-25 05:01 UTC, merged