fix: old pods are listed in new pod section for devtron apps deployed through Helm
devtron-labs/devtron pull request #4165
Opened 2023-10-26 18:14 UTC by ashishdevtron

# Description
These changes fix the flag condition which decides whether the pods are new or old

Fixes #4024 

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2023-10-27 05:41 UTC, kartik-579 requested changes

2023-10-27 05:41 UTC, kartik-579 commented on api/restHandler/AppListingRestHandler.go
> +				if _, ok := dataMap["isNew"]; !ok {
replace with constant

2023-10-27 05:41 UTC, kartik-579 commented on api/restHandler/AppListingRestHandler.go
> +			podMetadata := resourceTree["podMetadata"]
replace with constant

2023-10-27 05:41 UTC, kartik-579 commented on api/restHandler/AppListingRestHandler.go
> +			for _, data := range podMetadata.([]interface{}) {
is this type assertion always going to work? should add a validation for this

2023-10-27 05:41 UTC, kartik-579 commented on api/restHandler/AppListingRestHandler.go
> +				dataMap := data.(map[string]interface{})
check for assertion

2024-06-10 10:14 UTC, vikramdevtron commented
Outdated, Not required anymore

2024-06-10 10:14 UTC, closed without merging