fix: Remove duplicate key value in helm chart for kubelink configs
devtron-labs/devtron pull request #4239
Opened 2023-11-14 15:03 UTC by benosman

# Description

Since argocd is not yet on the cluster at the time of installing Devtron, I'm trying to bootstrap Devtron using fluxcd v2. It installs on the cluster using regular helm just fine, but fluxcd validates the output in a stricter manner.

It complains of a duplicate key entry for RUN_HELM_INSTALL_IN_ASYNC_MODE.

In the kubelink.configs section values.yaml,  a default for RUN_HELM_INSTALL_IN_ASYNC_MODE  is defined as false. In [templates/kubelink.yam](https://github.com/devtron-labs/devtron/blob/bfa491b25e36c3b5dfb21d3e19f396fbebdcfa46/charts/devtron/templates/kubelink.yaml#L32-L36)l there is a conditional that appends that same key below, meaning in the rendered output it appears twice.

This causes fluxcd to throw the error. [This issue](https://github.com/fluxcd/helm-controller/issues/283) is for a different helm chart, but it is along the same lines.

 # Fixes

Removed the redundant key from kubelink.configs defaults.

2023-12-18 07:07 UTC, pawan-mehta-dt commented
Hi @benosman please do this for devtron-bom.yaml file as well. We'll merge this during next release

2023-12-18 07:12 UTC, pawan-mehta-dt requested changes
Please check comments on PR

2023-12-18 22:32 UTC, benosman commented
> Hi @benosman please do this for devtron-bom.yaml file as well. We'll merge this during next release

Thanks for reviewing, extra commit added

2023-12-19 12:28 UTC, pawan-mehta-dt approved these changes

2023-12-19 12:29 UTC, merged