Doc: Added Application Groups Doc
devtron-labs/devtron pull request #4275
Opened 2023-11-22 14:56 UTC by ashokdevtron

2023-11-23 05:17 UTC, abhibhaw requested changes
RBAC is missing, who can create filters, who can trigger builds, what if I don't have same permission on all applications etc.

2023-11-23 11:59 UTC, ashokdevtron commented
> RBAC is missing, who can create filters, who can trigger builds, what if I don't have same permission on all applications etc.

Done 👍

2023-11-23 12:43 UTC, abhibhaw submitted a review, later dismissed
@uxarya-d Please confirm on the RBAC

2023-12-04 12:02 UTC, uxarya-d requested changes
Pls check comments

2023-12-04 12:02 UTC, uxarya-d commented on docs/user-guide/application-groups.md
> +Users need to have [Manager role](../user-guide/global-configurations/authorization/user-access.md#role-based-access-levels) or above (along with access to the environment and applications) to update
Admin role and above…

2023-12-06 07:36 UTC, uxarya-d approved these changes

2023-12-06 07:53 UTC, merged