chore: Integrate Cloudanix Image Scanner Plugin for Advanced Image Scanning
devtron-labs/devtron pull request #4396
Opened 2023-12-13 08:52 UTC by badal773

This pull request introduces integration of image scanning through Cloudanix Image Scanner.

2023-12-13 19:03 UTC, prakarsh-dt approved these changes

2023-12-14 09:11 UTC, kartik-579 requested changes

2023-12-14 09:11 UTC, kartik-579 commented on scripts/sql/202_cloudanix_imagescan.up.sql
> +(nextval('id_seq_plugin_step_variable'),(SELECT ps.id FROM plugin_metadata p inner JOIN plugin_step ps on ps.plugin_id=p.id WHERE p.name='Cloudanix Imagescan v1.0.0' and ps."index"=1 and ps.deleted=f
running same query again, can store the result in variable and use it

2023-12-14 10:49 UTC, kartik-579 approved these changes

2023-12-14 10:52 UTC, merged