Config diff
devtron-labs/devtron pull request #4619
Opened 2024-02-01 17:37 UTC by adi6859

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-02-02 08:33 UTC, subhashish-devtron commented on pkg/config/bean.go
> +	PublishedConfigState ConfigState = iota + 2
don't use iota

2024-02-02 08:34 UTC, subhashish-devtron commented on pkg/config/bean.go
> +	DeploymentTemplate ResourceType = "Deployment Template"
are these not defined already?

2024-02-02 08:35 UTC, subhashish-devtron commented on pkg/config/bean.go
> +type ConfigDefinition struct {
ConfigProperty

2024-02-02 08:38 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +	configMapRepository chartConfig.ConfigMapRepository
you cannot use repository directly

2024-02-02 08:40 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +	}
1. function name is improper
2. have one loop
3. don;t use index, create empty slice and append
3. too many errors... discuss with me

>

2024-02-02 11:16 UTC, adi6859 commented on pkg/config/DeploymentConfigurationService.go
> +	configMapRepository chartConfig.ConfigMapRepository
removed

2024-02-02 12:23 UTC, subhashish-devtron commented on api/restHandler/DeploymentConfigurationRestHandler.go
> +	enforcer                       casbin.Enforcer
remove enforcer from here

2024-02-02 12:28 UTC, adi6859 commented on api/restHandler/DeploymentConfigurationRestHandler.go
> +	enforcer                       casbin.Enforcer
done

2024-02-02 13:28 UTC, subhashish-devtron requested changes

2024-02-02 13:28 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +		"FROM config_map_app_level WHERE app_id = ?;"
why raw query, use go-pg for where clauses etc and can put your expression in select.
I think we had discussed this already

2024-02-02 13:28 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +	return cMCSNames, err
```go
	if err != nil && err != pg.ErrNoRows {
		impl.Logger.Errorw("error occurred while fetching CM/CS names ", "appId", appId, "err", err)
          return cMCSNames,err
	} 
	return cMCSNames, nil
```

2024-02-02 13:28 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +		"json_array_elements(secret_data::json->'secrets')->>'name' AS cs_name " +
once you break this expression as per go-pg, reuse this expression in both queries

2024-02-02 13:28 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +		"json_array_elements(secret_data::json->'secrets')->>'name' AS cs_name " +
also you can give a thought on parameterizing the repo method such that you can  have just one repo method instead of two

2024-02-02 13:28 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +func setConfigDataResponse(cMCSNames []chartConfig.CMCSNames, configDataResponse *ConfigDataResponse) *ConfigDataResponse {
this is not a setter, rename appropriately

2024-02-02 13:28 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +	}
len(cmcsNames) == 0

2024-02-02 13:28 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +}
Why not this?

```go
func (impl *DeploymentConfigurationServiceImpl) ConfigAutoComplete(appId int, envId int) (*ConfigDataResponse, error) {
	cMCSNamesAppLevel, cMCSNamesEnvLevel, err := impl.configMapService.FetchCmCsNamesAppAndEnvLevel(appId, envId)
	if err != nil {
		return nil, err
	}
	cmProperties := getConfigPropertyList(cMCSNamesAppLevel)
	csProperties := getConfigPropertyList(cMCSNamesEnvLevel)

	return &ConfigDataResponse{ResourceConfig: append(cmProperties, csProperties...)}, nil
}

func getConfigPropertyList(cMCSNames []chartConfig.CMCSNames) []ConfigProperty {

	properties := make([]ConfigProperty, 0)
	if len(cMCSNames) == 0 {
		return properties
	}

	for _, name := range cMCSNames {

		resourceType := CM
		if name.CSName != "" {
			resourceType = CS
		}
		properties = append(properties, getConfigProperty(name.CMName, resourceType, PublishedConfigState))

	}
	return properties
}
func getConfigProperty(name string, configType ResourceType, State ConfigState) ConfigProperty {
	return ConfigProperty{
		Name:        name,
		Type:        configType,
		ConfigState: State,
	}
}
```

2024-02-02 14:00 UTC, subhashish-devtron commented on pkg/config/DeploymentConfigurationService.go
> +	configDataResponse = setConfigDataResponse(cMCSNamesEnvLevel, configDataResponse)
this would append both app level and app-env level config maps and secrets and we will get duplicates

2024-02-08 05:57 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +	tableName := "config_map_env_level"
constant please

2024-02-08 05:57 UTC, subhashish-devtron commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +	tableName := "config_map_env_level"
below also

2024-02-13 14:57 UTC, adi6859 commented on internal/sql/repository/chartConfig/ConfigMapRepository.go
> +		Table(tableName).
name and type from db

2024-02-13 14:58 UTC, adi6859 commented on pkg/config/DeploymentConfigurationService.go
> +		if name.CMName != "" && !combinedNames[name.CMName] {
remove if condition when we get name and type

2024-06-10 10:57 UTC, vikramdevtron commented
outdated

2024-07-15 15:09 UTC, kartik-579 requested changes

2024-07-15 15:09 UTC, kartik-579 commented on api/restHandler/DeploymentConfigurationRestHandler.go
> +		handler.logger.Errorw("service err, ConfigAutoComplete ", "err", err)
log appId and envId

2024-07-15 15:09 UTC, kartik-579 commented on api/router/DeploymentConfigRouter.go
> +func (router DeploymentConfigurationRouterImpl) initDeploymentConfigurationRouter(configRouter *mux.Router) {
subrouter for orchestrator/config, should add deployment in route. also service does not aligns with the name and route, have to discuss this

2024-07-30 12:32 UTC, prakash100198 commented on pkg/configDiff/bean/bean.go
> +	PublishedConfigState ConfigState = 3
this has been removed, now we don't use enum, just simple string

2024-07-30 12:39 UTC, prakash100198 commented on pkg/pipeline/ConfigMapService.go
> +	cMCSNamesAppLevel, err := impl.configMapRepository.GetConfigNamesForAppAndEnvLevel(appId, -1)
<img width="1440" alt="Screenshot 2024-07-25 at 5 00 05 PM" src="https://github.com/user-attachments/assets/27b6d5a0-736c-4f19-af3e-0bf40f990382">
in ide it shows envId

2024-07-30 12:43 UTC, prakash100198 commented on pkg/configDiff/DeploymentConfigurationService.go
> +	cmcsKeyPropertyAppLevelMap, cmcsKeyPropertyEnvLevelMap := helper.GetCmCsAppAndEnvLevelMap(cMCSNamesAppLevel, cMCSNamesEnvLevel)
done

2024-09-09 10:36 UTC, closed without merging