feat: change deployment type from gitops to non-gitops and vice-versa for chart store apps
devtron-labs/devtron pull request #4666
Opened 2024-02-13 11:35 UTC by prakash100198

# Description

Fixes #

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-02-14 10:18 UTC, nishant-d requested changes

2024-02-14 10:18 UTC, nishant-d commented on api/appStore/InstalledAppRestHandler.go
> +	acdToken, err := handler.argoUserService.GetLatestDevtronArgoCdUserToken()
should be abstracted at ACD service layer

2024-02-14 10:18 UTC, nishant-d commented on api/appStore/InstalledAppRestHandler.go
> +	if ok := handler.enforcer.Enforce(token, casbin.ResourceHelmApp, casbin.ActionDelete, "*"); !ok {
action.create

2024-02-14 10:18 UTC, nishant-d commented on pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
> +		return response, &util.ApiError{HttpStatusCode: http.StatusNotFound, InternalMessage: "cluster unreachable", UserMessage: "cluster unreachable"}
change status to unreachable

2024-02-14 10:18 UTC, nishant-d commented on pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
> +func (impl *InstalledAppDeploymentTypeChangeServiceImpl) isClusterReachable(envId int) (bool, error) {
move it to env/cluster service

2024-02-14 19:35 UTC, prakash100198 commented on api/appStore/InstalledAppRestHandler.go
> +		handler.Logger.Errorw("request err, MigrateDeploymentTypeForChartStore", "err", err, "payload", migrateAndTriggerReq)
done

2024-02-14 19:35 UTC, prakash100198 commented on api/appStore/InstalledAppRestHandler.go
> +	if ok := handler.enforcer.Enforce(token, casbin.ResourceHelmApp, casbin.ActionDelete, "*"); !ok {
done

2024-02-14 19:35 UTC, prakash100198 commented on pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
> +		return response, &util.ApiError{HttpStatusCode: http.StatusNotFound, InternalMessage: "cluster unreachable", UserMessage: "cluster unreachable"}
done

2024-02-23 16:12 UTC, nishant-d approved these changes

2024-02-25 10:26 UTC, merged