doc: Doc for Lock Config
devtron-labs/devtron pull request #4732
Opened 2024-03-01 09:36 UTC by ashokdevtron

2024-03-02 14:54 UTC, abhibhaw reviewed
This looks great. A suggestion to add this as reference at all the places in docs where we have discussed about deployment template / configs in doc. [Example reference and its child pages](https://docs.devtron.ai/usage/applications/creating-application/deployment-template)

2024-03-04 10:56 UTC, uxarya-d requested changes
Added comments

2024-03-04 10:56 UTC, uxarya-d commented on docs/user-guide/global-configurations/lock-deployment-config.md
> +If you have selected 'Basic' mode instead of 'Advanced (YAML)', only unlocked keys would appear.
Even if some keys from the `Basic` view are locked, all keys included in `Basic` view will keep showing. The user can change values from the UI but would not be able to save changes to any locked key.

2024-03-04 10:56 UTC, uxarya-d commented on docs/user-guide/global-configurations/lock-deployment-config.md
> +    ![Figure 4: Referring Values.YAML File](https://devtron-public-asset.s3.us-east-2.amazonaws.com/images/global-configurations/lock-dt/side-by-side.jpg)
Suggestion: Can we remove this screenshot, the empty state does not seem to add much value. Also, the two sentences together would be better. (something like below)

Enter the keys inside the editor on the left-hand side, e.g., `autoscaling.MaxReplicas`. Use <a href="https://goessner.net/articles/JsonPath/index.html" target="_blank">JSONpath expressions</a> to enter specific keys, lists, or objects to lock.

2024-03-04 12:02 UTC, ashokdevtron commented
> This looks great. A suggestion to add this as reference at all the places in docs where we have discussed about deployment template / configs in doc. [Example reference and its child pages](https://docs.devtron.ai/usage/applications/creating-application/deployment-template)

Done

2024-03-04 12:11 UTC, abhibhaw approved these changes
LGTM

2024-03-04 13:18 UTC, uxarya-d approved these changes

2024-03-04 13:30 UTC, merged