Duplicate workflow name fixed
devtron-labs/devtron pull request #4841
Opened 2024-03-27 07:26 UTC by Laeeqdev

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-04-01 12:39 UTC, prakash100198 requested changes

2024-04-01 12:39 UTC, prakash100198 commented on api/restHandler/CoreAppRestHandler.go
> +		workflowName = fmt.Sprintf("%s-clone-%s", workflowName, util.Generate(4))
make a func for this, maybe something GenerateNewWorkflowName, also use this everywhere

2024-04-01 13:05 UTC, prakash100198 approved these changes
lgtm

2024-04-02 06:54 UTC, prakash100198 requested changes

2024-04-02 06:54 UTC, prakash100198 commented on api/restHandler/CoreAppRestHandler.go
> +	if err != nil && !errors.Is(err, pg.ErrNoRows) && !errors.Is(err, pg.ErrMultiRows) {
take this code in appworkflowservice and return if workflow exist or not

2024-04-02 06:54 UTC, prakash100198 commented on pkg/appWorkflow/AppWorkflowService.go
> +	workflow, err := impl.appWorkflowRepository.FindByNameAndAppId(req.Name, req.AppId)
make a func checkIfWorkflowExists func for checking if workflow exists or not

2024-04-02 12:27 UTC, prakash100198 submitted a review, later dismissed

2024-04-09 06:35 UTC, prakash100198 approved these changes

2024-04-09 07:14 UTC, kripanshdevtron approved these changes

2024-04-09 08:22 UTC, prakash100198 approved these changes

2024-04-09 08:32 UTC, merged