Run time main and binary
devtron-labs/devtron pull request #4858
Opened 2024-04-01 05:56 UTC by Laeeqdev

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-04-12 05:59 UTC, kartik-579 requested changes

2024-04-12 05:59 UTC, kartik-579 commented on WiringNilCheck.go
> +func skipUnnecessaryFiledsForCheck(fieldName, valName string) bool {
Fields spelling correct

2024-04-12 06:47 UTC, Laeeqdev commented on WiringNilCheck.go
> +func skipUnnecessaryFiledsForCheck(fieldName, valName string) bool {
corrected

2024-05-12 15:14 UTC, kripanshdevtron commented on tests/integrationTesting/migrator.yaml
> +              value: 606a33bc5e9b15d8b1c404f0dfbd1c70b21b4063
Need to make it config Driven.

2024-05-21 12:28 UTC, kripanshdevtron submitted a review, later dismissed

2024-05-21 14:31 UTC, kripanshdevtron approved these changes

2024-05-21 16:33 UTC, merged