fix: ci-cd count per day in telemetry data
devtron-labs/devtron pull request #4931
Opened 2024-04-12 04:57 UTC by komalreddy3

# Description

Fixes #4886

Added fields to TelemetryEventDto

1. ciTriggeredPerDay ( count of ci pipelines triggered in last 24hrs)
2. cdTriggeredPerDay ( count of cd pipelines triggered in last 24hrs)
3. ciDeletedPerDay ( count of ci pipelines deleted in last 24hrs)
4. cdDeletedPerDay ( count of cd pipelines deleted in last 24hrs)
5. Rename ciCountPerDay to ciCreatedPerDay ( count of ci pipelines created in last 24hrs)
6. Rename cdCountPerDay to cdCreatedPerDay ( count of cd pipelines created in last 24hrs)

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-04-12 08:08 UTC, Ash-exp requested changes

2024-04-12 08:08 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
> +	query := "SELECT count(DISTINCT(cd_workflow_id)) FROM cd_workflow_runner WHERE started_on > now() - interval '1 day'"
use go-pg to perform the same native query

2024-04-12 08:08 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
> +	query := "SELECT count(DISTINCT(cd_workflow_id)) FROM cd_workflow_runner WHERE started_on > now() - interval '1 day'"
cd_workflow_runner has 3 runner types: PRE/ POST/ DEPLOY. we'll fetch the deployments only I guess. verify it from Product.

2024-04-12 08:08 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
> +	query := "SELECT count(DISTINCT(ci_pipeline_id)) FROM ci_workflow WHERE started_on > now() - interval '1 day'"
use go-pg to achieve the same query

2024-04-15 07:01 UTC, Ash-exp submitted a review, later dismissed
LGTM

2024-04-16 09:30 UTC, Ash-exp approved these changes

2024-04-19 07:47 UTC, Ash-exp requested changes

2024-04-19 07:47 UTC, Ash-exp commented on internal/sql/repository/dockerRegistry/DockerArtifactStoreRepository.go
> +		Column("docker_artifact_store.*", "IpsConfig", "OCIRegistryConfig").
"IpsConfig", "OCIRegistryConfig" relations can be dropped

2024-04-19 07:47 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/CiPipelineRepository.go
>  		Column("ci_pipeline.*").
do we require all columns, ci_pipeline.*. I guess just ci_pipeline.id will do

2024-04-19 07:47 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/CiPipelineRepository.go
> +		Column("ci_pipeline.*").
same here

2024-04-19 07:47 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/PipelineRepository.go
>  		Column("pipeline.*").
same here

2024-04-19 07:47 UTC, Ash-exp commented on internal/sql/repository/pipelineConfig/PipelineRepository.go
> +		Column("pipeline.*").
here

2024-04-19 07:47 UTC, Ash-exp commented on pkg/cluster/repository/EnvironmentRepository.go
> +		Column("environment.*", "Cluster").
drop the cluster join

2024-04-19 10:09 UTC, nishant-d requested changes

2024-04-19 10:09 UTC, nishant-d commented on internal/sql/repository/pipelineConfig/CiPipelineRepository.go
> +		Column("ci_pipeline.id").
do we need `Column("ci_pipeline.id").` here

2024-04-19 10:09 UTC, nishant-d commented on internal/sql/repository/pipelineConfig/CiPipelineRepository.go
> +		Column("ci_pipeline.id").
do we need `Column("ci_pipeline.id").` here

2024-04-19 10:09 UTC, nishant-d commented on internal/sql/repository/GitOpsConfigRepository.go
> +	cnt, err := impl.dbConnection.Model(&GitOpsConfig{}).Order("updated_on desc").Count()
.Order("updated_on desc")

2024-04-19 10:56 UTC, nishant-d approved these changes

2024-04-22 10:08 UTC, Ash-exp approved these changes

2024-04-22 11:12 UTC, merged