fixed
devtron-labs/devtron pull request #4973
Opened 2024-04-19 07:16 UTC by ShashwatDadhich

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-04-22 11:19 UTC, nishant-d requested changes

2024-04-22 11:19 UTC, nishant-d commented on client/argocdServer/application/Application.go
> +		podsMetadataFromPods := buildPodMetadataFromPod(resp, podManifests, newPodNames)
extract this as separate function

2024-05-14 06:52 UTC, prakash100198 approved these changes

2024-05-14 08:34 UTC, nishant-d approved these changes

2024-05-14 08:51 UTC, merged