fix: deleted api token can be reused if created again with same name
devtron-labs/devtron pull request #4978
Opened 2024-04-19 12:05 UTC by ashishdevtron

# Description

introduced api token versioning to keep track of deleted/old tokens

Fixes #4960

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-04-22 13:35 UTC, nishant-d requested changes

2024-04-22 13:35 UTC, nishant-d commented on pkg/apiToken/ApiTokenRepository.go
> +		Where("version = ?", previousVersion).
use ID in where clause

2024-04-22 13:35 UTC, nishant-d commented on pkg/apiToken/ApiTokenRepository.go
> +		return fmt.Errorf(ConcurrentTokenUpdateRequest)
version not found/ version mismatch

2024-04-22 13:35 UTC, nishant-d commented on pkg/apiToken/ApiTokenService.go
> +		previousVersion int
previousTokenVersion

2024-04-22 13:35 UTC, nishant-d commented on pkg/apiToken/ApiTokenService.go
> +		err = impl.apiTokenRepository.UpdateIf(apiTokenSaveRequest, previousVersion)
add comment

2024-04-22 13:35 UTC, nishant-d commented on pkg/auth/user/UserAuthService.go
> +		isProvidedTokenValid, err := impl.userRepository.CheckIfUserIsValidByTokenNameAndVersion(tokenName, embeddedTokenVersion)
backward compatibility

2024-04-22 13:35 UTC, nishant-d commented on pkg/auth/user/UserService.go
> +	if userInfo.UserType == bean.USER_TYPE_API_TOKEN {
make it common function

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/apiToken/ApiTokenRepository.go
> +		Where("version = ?", previousVersion).
done

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/apiToken/ApiTokenRepository.go
> +		return fmt.Errorf(ConcurrentTokenUpdateRequest)
done

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/apiToken/ApiTokenService.go
> +		previousVersion int
done

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/apiToken/ApiTokenService.go
> +		err = impl.apiTokenRepository.UpdateIf(apiTokenSaveRequest, previousVersion)
done

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/auth/user/UserAuthService.go
> +		isProvidedTokenValid, err := impl.userRepository.CheckIfUserIsValidByTokenNameAndVersion(tokenName, embeddedTokenVersion)
done

2024-04-22 17:01 UTC, ashishdevtron commented on pkg/auth/user/UserService.go
> +	if userInfo.UserType == bean.USER_TYPE_API_TOKEN {
done

2024-04-22 17:09 UTC, nishant-d requested changes

2024-04-22 17:09 UTC, nishant-d commented on pkg/auth/user/UserService.go
> +	if userInfo.UserType == bean.USER_TYPE_API_TOKEN && len(version) > 0 {
add comment around length

2024-04-22 17:09 UTC, nishant-d commented on pkg/auth/user/repository/UserRepository.go
> +	query := "SELECT t.version FROM api_token t WHERE t.name = ?"
why native query ?

2024-04-22 17:09 UTC, nishant-d commented on pkg/auth/user/repository/UserRepository.go
> +	return dbTokenVersion == tokenVersion, nil
we can add version comparison inside where clause itself

2024-04-23 02:29 UTC, nishant-d requested changes

2024-04-23 02:29 UTC, nishant-d commented on pkg/auth/user/UserService.go
> +		if err != nil || !isProvidedTokenValid {
duplicate code

2024-04-23 02:29 UTC, nishant-d commented on pkg/auth/user/helper/helper.go
> +func CheckIfTokenIsValid(email string, version string, userRepository repository.UserRepository) (bool, error) {
we shouldn't make db call from helper/util

2024-04-23 09:16 UTC, nishant-d submitted a review, later dismissed

2024-04-26 12:37 UTC, nishant-d approved these changes

2024-04-26 12:37 UTC, merged