log.Fatal Removed
devtron-labs/devtron pull request #5043
Opened 2024-05-02 05:51 UTC by ShashwatDadhich

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-05-03 11:41 UTC, nishant-d requested changes

2024-05-03 11:44 UTC, nishant-d requested changes

2024-05-03 11:44 UTC, nishant-d commented on client/argocdServer/connection/proxy.go
> +		log.Println(err)
propagate error at startup

2024-05-07 12:46 UTC, ShashwatDadhich commented on pkg/module/ModuleCacheService.go
> +		log.Println("not able to get k8s cluster rest config.", "error", err)
done

2024-05-07 12:46 UTC, ShashwatDadhich commented on client/argocdServer/connection/proxy.go
> +		log.Println(err)
done

2024-05-07 12:46 UTC, ShashwatDadhich commented on pkg/auth/authorisation/casbin/Adapter.go
>  	log.Println("casbin Policies Loaded Successfully")
done

2024-05-07 12:50 UTC, ShashwatDadhich commented on fetchAllEnv/fetchAllEnv.go
> +		log.Println("error parsing file:", err)
done

2024-05-07 13:50 UTC, nishant-d requested changes

2024-05-07 13:50 UTC, nishant-d commented on client/grafana/proxy.go
> +		return func(writer http.ResponseWriter, request *http.Request) {
remove error function

2024-05-07 13:50 UTC, nishant-d commented on client/grafana/proxy.go
> +		return func(writer http.ResponseWriter, request *http.Request) {
true for all

2024-05-07 13:50 UTC, nishant-d commented on pkg/module/ModuleCacheService.go
> +		log.Println("Error while saving module.", "moduleName", moduleName, "error", err)
return error

2024-05-07 13:50 UTC, nishant-d commented on pkg/server/ServerCacheService.go
> +			log.Println("got error in fetching devtron helm release values.", "error", err)
return error

2024-05-09 13:20 UTC, nishant-d submitted a review, later dismissed

2024-05-20 07:34 UTC, nishant-d approved these changes

2024-05-20 07:36 UTC, merged