Feature: Flux App Listing
devtron-labs/devtron pull request #5250
Opened 2024-06-05 14:50 UTC by RajeevRanjan27

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-06-05 18:45 UTC, prakash100198 requested changes

2024-06-05 18:45 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +	clusterIdString := v.Get("clusterIds")
There's a func in codebase called as "ExtractIntArrayQueryParam" which exactly serves this purpose, explore that and use that here

2024-06-05 18:45 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +		handler.logger.Errorw("error in listing all argo applications", "err", err, "clusterIds", clusterIds)
error in listing all argo applications -> error in listing all flux applications

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +	ConvertClusterBeanToClusterConfig(clusters []*cluster.ClusterBean) ([]*gRPC.ClusterConfig, error)
why are we binding this method to this interface since it's not used by any other external interfaces

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +	//helmAppService service.HelmAppService
uncomment, this is required

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +		//for _, clusterId := range clusterIds {
uncomment

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +			impl.logger.Errorw("error in getting all active clusters", "err", err1)
make sure to change error messaging after copying and pasting somewhere

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +		fluxApplicationList, err1 := applicationStream.Recv()
no need to assign err as "err1" just use "err" only , reassigning err will anyway make sure that new error is in err variable

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +	if err == nil {
do if err!=nil operation first then in else block do this part

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +func (impl *FluxApplicationServiceImpl) ConvertClusterBeanToClusterConfig(clusters []*cluster.ClusterBean) ([]*gRPC.ClusterConfig, error) {
I think we already have this function defined somewhere, could you  please look for that and reuse that instead of creating a new one

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/bean/bean.go
> +	//DevtronCDNamespae            = "devtroncd"
please remove unwanted codes

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/bean/bean.go
> +	FluxHelmReleaseVersion   = "v2"
FluxHelmReleaseVersion -> FluxHelmReleaseVersionV2

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/bean/bean.go
> +	FluxKustomizationVersion = "v1"
FluxKustomizationVersion - > FluxKustomizationVersionV1

2024-06-05 18:45 UTC, prakash100198 commented on temp/output.env
> +OUTPUT=17
do we need this change?

2024-06-05 18:45 UTC, prakash100198 commented on pkg/fluxApplication/bean/bean.go
> +}
Can you pls explain the purpose of these vars and I can only see initialisation and not implemented somewhere

2024-06-06 09:14 UTC, prakash100198 requested changes

2024-06-06 09:14 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +	clusterIdString := v.Get("clusterIds")
also comment here that we are using empty clusterids for fetching all cluster details

2024-06-06 09:14 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +		return
no need to put return here, WriteJsonResp will handle that

2024-06-06 09:14 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +			return
return -> common.WriteJsonResp(w, err, nil, http.StatusInternalServerError)

2024-06-06 09:14 UTC, prakash100198 commented on api/fluxApplication/FluxApplicationRestHandler.go
> +		return
no need of return here common.WriteJsonResp handles that

2024-06-06 09:14 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +		impl.logger.Errorw("error while fetching list application from kubelink", "err", err)
error while fetching list application from kubelink -> error while fetching flux application list

2024-06-10 08:20 UTC, prakash100198 requested changes

2024-06-11 10:10 UTC, nishant-d submitted a review, later dismissed

2024-06-12 11:50 UTC, prakash100198 submitted a review, later dismissed

2024-06-19 06:18 UTC, closed without merging