feat: Flux added functionaities
devtron-labs/devtron pull request #5457
Opened 2024-07-08 11:02 UTC by RajeevRanjan27

# Description

Fixes https://github.com/devtron-labs/devtron/issues/5332

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-07-08 11:54 UTC, prakash100198 requested changes

2024-07-08 11:54 UTC, prakash100198 commented on api/k8s/application/k8sApplicationRestHandler.go
> +			common.WriteJsonResp(w, errors.New("unauthorized"), nil, http.StatusForbidden)
Do everywhere as written above, extract out in a rbac func, 
in most of the cases one rbac func will work for all

2024-07-09 12:59 UTC, RajeevRanjan27 commented on api/k8s/application/k8sApplicationRestHandler.go
> +			common.WriteJsonResp(w, errors.New("unauthorized"), nil, http.StatusForbidden)
yes, extracted and done for the get, update and delete related queries, as it invloves the validation of resources as well

2024-07-09 13:30 UTC, prakash100198 requested changes

2024-07-09 13:30 UTC, prakash100198 commented on api/k8s/application/k8sApplicationRestHandler.go
> +		} else if ok == false {
else if ok == false -> else if !ok

2024-07-09 13:30 UTC, prakash100198 commented on api/k8s/application/k8sApplicationRestHandler.go
>  	}
appIdString

2024-07-09 13:30 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +func (impl *FluxApplicationServiceImpl) UnHibernateFluxApplication(ctx context.Context, app *bean.FluxAppIdentifier, hibernateRequest *openapi.HibernateRequest) ([]*openapi.HibernateStatus, error) {
log error using impl.logger.Errorw

2024-08-23 11:15 UTC, closed without merging

2024-08-23 11:15 UTC, RajeevRanjan27 commented
https://github.com/devtron-labs/devtron/pull/5528