feat: ext argo app rbac and missing common features
devtron-labs/devtron pull request #5528
Opened 2024-07-19 05:47 UTC by RajeevRanjan27

# Description

Fixes https://github.com/devtron-labs/devtron/issues/5527

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-07-23 09:25 UTC, prakash100198 requested changes

2024-07-23 09:25 UTC, prakash100198 commented on pkg/argoApplication/ArgoApplicationService.go
> +	//conf, err := impl.helmAppService.GetClusterConf(app.ClusterId)
remove

2024-07-23 09:25 UTC, prakash100198 commented on pkg/argoApplication/ArgoApplicationService.go
> +		impl.logger.Errorw("HibernateArgoApplication", "error in hibernating the requested resource", err, "clusterId", app.ClusterId)
log identifier name for better debugging

2024-07-23 09:25 UTC, prakash100198 commented on pkg/argoApplication/ArgoApplicationService.go
> +	//conf, err := impl.helmAppService.GetClusterConf(app.ClusterId)
remove

2024-07-23 09:25 UTC, prakash100198 commented on pkg/fluxApplication/FluxApplicationService.go
> +		impl.logger.Errorw("HibernateFluxApplication", "error in hibernating the requested resource", err, "clusterId", app.ClusterId)
log app name

2024-08-09 11:09 UTC, prakash100198 approved these changes

2024-08-09 11:32 UTC, nishant-d approved these changes

2024-08-09 11:42 UTC, vikramdevtron approved these changes

2024-08-09 13:14 UTC, merged