feat: refactoring deployment app name usage
devtron-labs/devtron pull request #5702
Opened 2024-08-21 05:43 UTC by iamayushm

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-08-21 14:20 UTC, kartik-579 requested changes

2024-08-21 14:20 UTC, kartik-579 commented on scripts/sql/274_system_controller.down.sql
why have we done all these sql file renaming changes

2024-08-22 12:29 UTC, kartik-579 submitted a review, later dismissed

2024-08-22 12:46 UTC, kartik-579 approved these changes

2024-08-22 13:24 UTC, vikramdevtron approved these changes

2024-08-22 13:30 UTC, kartik-579 approved these changes

2024-08-22 13:31 UTC, vikramdevtron approved these changes

2024-08-23 05:39 UTC, merged