doc: Added Clone Pipeline Config
devtron-labs/devtron pull request #5793
Opened 2024-09-04 07:42 UTC by ashokdevtron

- Added **Clone Pipeline Configuration** section in Application Group doc.
- Use Case added
- RBAC added
- Enterprise Tag added
- Snapshots and GIFs added
- Interlinking added in **CD Pipeline** doc in Workflow section

2024-09-05 16:13 UTC, abhibhaw requested changes
We should aim to use(from next time) examples which are relatable to users rather than doc1 and doc2

2024-09-05 16:13 UTC, abhibhaw commented on docs/user-guide/application-groups.md
> +Only superadmins can clone pipeline configuration.
wording needs to be changed if heading gets updated

2024-09-05 16:13 UTC, abhibhaw commented on docs/user-guide/application-groups.md
> +* Scripts/Plugins from Pre-CI, Post-CI, Pre-CD, Post-CD
we had a list in PRD, what gets cloned and what not, maybe we can add that here

2024-09-05 16:13 UTC, abhibhaw commented on docs/user-guide/application-groups.md
> +2. **Source Workflow**: Uses the same workflow but clones only its existing CD pipeline. Allows you to utilize the original CI source available for source environment.
the sentence needs more clarification

2024-09-24 13:59 UTC, ashokdevtron commented
Copied to the new repo and fixed in this PR: https://github.com/devtron-labs/devtron-documentation/pull/7

2024-09-24 13:59 UTC, closed without merging