Feature: app labels tagging
devtron-labs/devtron pull request #580
Opened 2021-07-15 06:10 UTC by vikramdevtron

# Description

this feature allow you to tag multiple tags to application, help you to categorize, and search your applications.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Backend Api's tested

- [ ] Create App, with labels, without labels, empty labels etc.
- [ ] Edit labels on apps, add and remove labels.
- [ ] app meta info api.

# Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have tested it for all user roles

2021-08-23 16:23 UTC, nishant-d requested changes

2021-08-23 16:23 UTC, nishant-d commented on api/restHandler/AppLabelsRestHandler.go
> +type AppLabelRestHandler interface {
RBAC impl missing

2021-08-23 16:23 UTC, nishant-d commented on docs/user-guide/app-labels.md
> +`TODO` : visual
please add visuals and remove TODO

2021-08-23 16:23 UTC, nishant-d commented on internal/sql/repository/pipelineConfig/AppLabelsRepository.go
> +	AppId     int      `sql:"app_id"`
can appId be null?

2021-08-23 16:23 UTC, nishant-d commented on scripts/sql/21_create_app_label.up.sql
> +    "id"         int4 NOT NULL DEFAULT nextval('id_seq_app_label'::regclass),
not null constraint missing

2021-08-24 03:53 UTC, vikramdevtron commented on api/restHandler/AppLabelsRestHandler.go
> +type AppLabelRestHandler interface {
added

2021-08-24 03:53 UTC, vikramdevtron commented on internal/sql/repository/pipelineConfig/AppLabelsRepository.go
> +	AppId     int      `sql:"app_id"`
added

2021-08-24 03:53 UTC, vikramdevtron commented on scripts/sql/21_create_app_label.up.sql
> +    "id"         int4 NOT NULL DEFAULT nextval('id_seq_app_label'::regclass),
added

2021-08-24 03:53 UTC, vikramdevtron commented on docs/user-guide/app-labels.md
> +`TODO` : visual
added

2021-08-24 05:44 UTC, nishant-d approved these changes

2021-08-24 05:45 UTC, merged