doc: GKE Provisioner doc
devtron-labs/devtron pull request #5836
Opened 2024-09-12 13:03 UTC by bhushan-nemade-dt

# Description

Fixes #5835 

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-09-12 16:57 UTC, abhibhaw requested changes

2024-09-12 16:57 UTC, abhibhaw commented on docs/user-guide/plugins/gke-provisioner.md
> +1. Go to Applications → **Devtron Apps**.
We don't need an application to provision GKE, that's not the its purpose. Please go ahead with the job flow : )

2024-09-18 06:37 UTC, ashokdevtron commented on docs/user-guide/plugins/gke-provisioner.md
> +Before integrating the **GKE Provisioner** plugin make sure that you have an GCP account with valid permissions to provision GKE.
Replace `an GCP account` with a `GCP account`

2024-12-31 10:38 UTC, satyampsoni commented
Closing this pr with refrence  to the [doc: GKE Provisioner Doc](https://github.com/devtron-labs/devtron-documentation/pull/3)

2024-12-31 10:38 UTC, closed without merging