feat: Config diff 3 oss
devtron-labs/devtron pull request #5837
Opened 2024-09-12 21:13 UTC by prakash100198

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-09-26 07:55 UTC, vikramdevtron commented on api/router/DeploymentConfigRouter.go
> +		Methods("POST")
backward compatibility ? new orchestrator build with old dashboard build

2024-09-26 09:54 UTC, prakash100198 commented on api/router/DeploymentConfigRouter.go
> +		Methods("POST")
done

2024-10-10 14:05 UTC, gireesh-naidu approved these changes

2024-10-15 13:27 UTC, gireesh-naidu approved these changes

2024-10-17 07:10 UTC, kartik-579 requested changes

2024-10-17 07:10 UTC, kartik-579 commented on pkg/generateManifest/DeploymentTemplateService.go
> +	}
move with other adapters

2024-10-17 07:10 UTC, kartik-579 commented on pkg/generateManifest/DeploymentTemplateService.go
> +	result.Data = *manifest.Manifest
manifest nil check

2024-10-17 07:10 UTC, kartik-579 commented on pkg/pipeline/history/ConfigMapHistoryService.go
> +	}
same marshal unmarshal flow as before

2024-10-17 07:44 UTC, prakash100198 commented on pkg/configDiff/DeploymentConfigurationService.go
> +		RequestDataMode:             generateManifest.Values,
no this is correct, had to pass Values or else the function where this is being passed will give manifest as response.

2024-10-17 09:45 UTC, kartik-579 approved these changes

2024-10-17 10:18 UTC, nishant-d approved these changes

2024-10-17 10:22 UTC, merged