fix: rbac fix for external ci change source
devtron-labs/devtron pull request #5846
Opened 2024-09-16 14:30 UTC by RajeevRanjan27

# Description

Fixes https://github.com/devtron-labs/sprint-tasks/issues/905

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-09-16 17:45 UTC, Ash-exp requested changes

2024-09-17 06:16 UTC, Ash-exp approved these changes

2024-09-17 08:40 UTC, gireesh-naidu approved these changes

2024-09-18 14:02 UTC, Ash-exp commented
Released in PR https://github.com/devtron-labs/devtron/pull/5845

2024-09-18 14:02 UTC, closed without merging