Fix: app update migration
devtron-labs/devtron pull request #5903
Opened 2024-09-25 10:49 UTC by iamayushm

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-09-25 11:09 UTC, nishant-d requested changes

2024-09-25 11:09 UTC, nishant-d commented on pkg/app/AppCrudOperationService.go
> +				err := impl.appRepository.Update(activeApp)
log

2024-09-25 11:09 UTC, nishant-d commented on pkg/app/AppCrudOperationService.go
> +	if err == pg.ErrMultiRows {
extract as function

2024-09-26 07:30 UTC, vikramdevtron approved these changes

2024-09-26 08:29 UTC, nishant-d approved these changes

2024-09-26 08:35 UTC, merged