fix: helm rollback in case of no gitops
devtron-labs/devtron pull request #6005
Opened 2024-10-21 05:36 UTC by RajeevRanjan27

# Description

Fixes https://github.com/devtron-labs/devops-sprint/issues/1011

## Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have performed a self-review of my own code.
* [x] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-10-21 06:41 UTC, Ash-exp requested changes

2024-10-21 06:41 UTC, Ash-exp commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +	} else if installedApp.DeploymentAppType == util.PIPELINE_DEPLOYMENT_TYPE_HELM && installedApp.Id > 0 {
use util.IsHelmApp(deploymentConfig.DeploymentAppType) and remove unnecessary check installedApp.Id > 0

2024-10-21 06:41 UTC, Ash-exp commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +	if installedApp.Id == 0 {
make a common const for this. has been evaluated multiple times

2024-10-21 06:41 UTC, Ash-exp commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +			UserId: userId,
use builder patterns to populate the DTO

2024-10-21 06:41 UTC, Ash-exp commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +		if installedAppVersionHistory.Status == "Healthy" || installedAppVersionHistory.Status == "Succeeded" {
bind a method to installedAppVersionHistory. IsSuccessful()

2024-10-22 14:25 UTC, Ash-exp requested changes

2024-10-22 14:25 UTC, Ash-exp commented on pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
> +	GetInstalledAppVersionAny(id int, userId int32) (*appStoreBean.InstallAppVersionDTO, error)
rename to `GetInstalledAppVersionByIdIncludeDeleted`

2024-10-23 06:56 UTC, Ash-exp approved these changes

2024-10-28 21:09 UTC, iamayushm commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +			upgradeRequest.Id = 0
id should be zero only when chart is changed and not version, verify

2024-10-28 21:34 UTC, iamayushm commented on pkg/appStore/adapter/Adapter.go
> +func GenerateUpdateRequestDTO(request *appStoreBean.InstallAppVersionDTO, installedApp *appStoreBean.InstallAppVersionDTO, installedAppVersionHistory *repository.InstalledAppVersionHistory, installed
can be renamed to updateRequestDTOForRollback or something similar

2024-10-28 21:35 UTC, iamayushm commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +		if installedApp.AppStoreVersion != installedAppVersionDTO.AppStoreVersion {
this logic can be moved to GenerateUpdateRequestDTO

2024-10-28 21:41 UTC, iamayushm commented on pkg/appStore/installedApp/service/AppStoreDeploymentService.go
> +	err = impl.attributesService.UpdateKeyValueByOne(bean2.HELM_APP_UPDATE_COUNTER)
this value should be update irrespective of update is success/failure, move this back to rest handler

2024-10-28 21:45 UTC, iamayushm approved these changes

2024-10-28 21:53 UTC, iamayushm reviewed
please check rollback for apps installed in EA mode, that should we also modify this check "util2.IsHelmApp(installedApp.AppOfferingMode)" in GetDeploymentHistory function to installedAppId>0 . did we checked this case in QA?

2024-11-04 11:45 UTC, RajeevRanjan27 commented
> please check rollback for apps installed in EA mode, that should we also modify this check "util2.IsHelmApp(installedApp.AppOfferingMode)" in GetDeploymentHistory function to installedAppId>0 . did we checked this case in QA?

> for ea mode rollback we have handled the case inside the `GetDeploymentHistory` function with `installedAppId>0`

2024-11-04 12:38 UTC, iamayushm approved these changes

2024-11-04 12:40 UTC, vikramdevtron approved these changes

2024-11-04 12:41 UTC, merged