fix: modified the queries for the up and down of 300 and 304
devtron-labs/devtron pull request #6120
Opened 2024-11-20 20:16 UTC by RajeevRanjan27

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-11-20 20:23 UTC, prakash100198 requested changes

2024-11-20 20:23 UTC, prakash100198 commented on scripts/sql/30002300_appoval_email_template_subject_update.down.sql
this down script is not correct, conditions should match the corresponding up script

2024-11-21 07:13 UTC, prakash100198 approved these changes

2024-11-21 07:17 UTC, vikramdevtron approved these changes

2024-11-21 07:17 UTC, merged