Image scan fixes oss
devtron-labs/devtron pull request #6156
Opened 2024-12-04 07:30 UTC by prakash100198

# Description

Fixes #

## Checklist:

* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Does this PR requires documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have performed a self-review of my own code.
* [ ] I have commented my code, particularly in hard-to-understand areas.
* [ ] I have tested it for all user roles.
* [ ] I have added all the required unit/api test cases.

## Does this PR introduce a user-facing change?

```release-note

```

2024-12-04 09:59 UTC, Shivam-nagar23 requested changes

2024-12-04 09:59 UTC, Shivam-nagar23 commented on pkg/pipeline/repository/PipelineStageRepository.go
> +	if stageType.IsStageTypePostCi() || stageType.IsStageTypePostCi() {
Correct this, pre ci and pre cd

2024-12-04 09:59 UTC, Shivam-nagar23 commented on pkg/workflow/dag/helper/helper.go
> +		AuditLog:           sql.AuditLog{CreatedBy: request.UserId, UpdatedBy: request.UserId, CreatedOn: createdOn, UpdatedOn: updatedOn},
move to adapter

2024-12-05 14:18 UTC, Shivam-nagar23 submitted a review, later dismissed

2024-12-05 19:26 UTC, prakash100198 commented on pkg/workflow/dag/WorkflowDagExecutor.go
> +	pipelineStage := repository4.PIPELINE_STAGE_TYPE_POST_CI
done

2024-12-16 08:16 UTC, merged