updated common labels on each micro-services
devtron-labs/devtron pull request #624
Opened 2021-08-03 09:28 UTC by pawan-59

# Description

Updated common labels  on each micro-services. Now every micro-services on different cluster can be filter out with same label.

2021-08-03 10:30 UTC, nishant-d requested changes

2021-08-03 11:07 UTC, pawan-59 commented on manifests/yamls/gitsensor.yaml
> +    component: gitsensor
changed as per you suggestion.

2022-09-06 04:03 UTC, prakarsh-dt commented
@pawan-59 Can you review this please and resolve conflicts?

2023-12-18 06:59 UTC, abhibhaw commented
This one is not required now

2023-12-18 06:59 UTC, closed without merging