Gitops Config Validation
devtron-labs/devtron pull request #688
Opened 2021-09-02 08:03 UTC by kartik-579

# Description

In the current support for Gitops configuration, the validation for the same is not implemented when it is being provided by the user. Added validation at the step when a configuration is saved/updated.

# How Has This Been Tested?
The feature is tested on localhost as well as a demo environment for all the 3 providers, i.e. GitHub, GitLab, Azure.

2021-09-02 13:33 UTC, vikramdevtron commented on internal/util/GitService.go
> +type GitOpsConfigDtoTemp struct {
redundant GitOpsConfigDtoTemp, move it to common DTO.

2021-09-02 13:33 UTC, vikramdevtron commented on internal/util/GitService.go
> +	err := impl.DeleteProject(name)
log error

2021-09-02 13:33 UTC, vikramdevtron commented on internal/util/GitService.go
> +		detailedError.StageErrorMap["GetRepoUrl"] = err
use Constant for Key

2021-09-02 13:33 UTC, vikramdevtron commented on internal/util/GitService.go
> +		detailedError.StageErrorMap["CLoneHttp"] = err
use Constant for Key

2021-09-02 13:33 UTC, vikramdevtron commented on internal/util/GitService.go
> +	detailedError.SuccessfulStages = append(detailedError.SuccessfulStages, "CloneSsh")
add "CloneSsh" to Constant , or other similar items

2021-09-02 16:10 UTC, kartik-579 commented on internal/sql/repository/GitOpsConfigRepository.go
> +	Provider         string    `sql:"provider"`
not needed as this table is only used for storing the latest validation status and not for every config

2021-09-03 13:09 UTC, nishant-d requested changes

2021-09-06 05:38 UTC, nishant-d approved these changes

2021-09-06 07:44 UTC, nishant-d approved these changes

2021-09-06 08:03 UTC, nishant-d approved these changes

2021-09-06 08:04 UTC, merged