Delete options
devtron-labs/devtron pull request #937
Opened 2021-12-05 20:09 UTC by kartik-579

Add support for various delete options.

2022-02-02 09:10 UTC, pghildiyal commented on api/cluster/ClusterRestHandler.go
> +	impl.logger.Errorw("request payload, Update", "payload", bean)
this log should not be errorw

2022-02-02 09:11 UTC, pghildiyal commented on api/cluster/ClusterRouter.go
> +		Methods("POST").
this should be DELETE not POST

2022-02-02 09:12 UTC, pghildiyal commented on api/cluster/ClusterRestHandler.go
> +func (impl ClusterRestHandlerImpl) DeleteFromDb(w http.ResponseWriter, r *http.Request) {
in env its delete.. here deletefromdb... why this difference?

2022-02-02 09:22 UTC, pghildiyal commented on api/cluster/EnvironmentRestHandler.go
> +	impl.logger.Errorw("request payload, Delete", "payload", bean)
dont user errorw for normal logging

2022-02-02 09:23 UTC, pghildiyal commented on api/cluster/EnvironmentRouter.go
> +		Methods("POST").
should be DELETE

2022-02-02 09:24 UTC, pghildiyal commented on api/restHandler/AppStoreRestHandler.go
> +	deleteServiceFullMode delete2.DeleteServiceFullMode) *AppStoreRestHandlerImpl {
Can we have better name for the file DeleteServiceFullMode

2022-02-02 09:24 UTC, pghildiyal commented on api/restHandler/AppStoreRestHandler.go
> +func (handler *AppStoreRestHandlerImpl) DeleteChartRepo(w http.ResponseWriter, r *http.Request) {
Here we have DeleteChartRepo as the function name

2022-02-02 09:29 UTC, pghildiyal commented on api/restHandler/NotificationRestHandler.go
> +		cErr := impl.slackService.DeleteNotificationConfig(deleteReq, userId)
we should not call two different notification service in rest handler, they should be done from inside service

2022-02-02 12:37 UTC, pghildiyal commented on api/router/AppStoreRouter.go
> +		HandlerFunc(router.appStoreRestHandler.DeleteChartRepo).Methods("POST")
use DELETE instead of POST

2022-02-02 12:37 UTC, pghildiyal commented on api/router/ChartGroupRouter.go
> +	chartGroupRouter.Path("/delete").
use DELETE instead of POST

2022-02-02 12:39 UTC, pghildiyal commented on api/router/DockerRegRouter.go
> +		HandlerFunc(impl.dockerRestHandler.DeleteDockerRegistryConfig).
DELETE instead of POST

2022-02-02 12:39 UTC, pghildiyal commented on api/router/GitProviderRouter.go
> +		Methods("POST")
DELETE instead of post and also we can remove delete from the url.. from other places too

2022-02-02 12:39 UTC, pghildiyal commented on api/router/NotificationRouter.go
> +		HandlerFunc(impl.notificationRestHandler.DeleteNotificationChannelConfig).
remove delete from url and DELETE instead of POST

2022-02-02 12:40 UTC, pghildiyal commented on api/router/PipelineConfigRouter.go
> +	configRouter.Path("/material/delete").HandlerFunc(router.restHandler.DeleteMaterial).Methods("POST")
remove delete from url and DELETE instead of POST

2022-02-02 12:40 UTC, pghildiyal commented on api/team/TeamRouter.go
> +	configRouter.Path("/delete").HandlerFunc(impl.teamRestHandler.DeleteTeam).Methods("POST")
remove delete from url and DELETE instead of POST

2022-02-11 09:22 UTC, nishant-d requested changes

2022-02-11 09:23 UTC, nishant-d requested changes

2022-02-11 09:23 UTC, nishant-d commented on api/restHandler/NotificationRestHandler.go
> +	err = json.NewDecoder(ioutil.NopCloser(bytes.NewBuffer(data))).Decode(&channelReq)
use r.body directly

2022-02-11 10:55 UTC, pghildiyal approved these changes

2022-02-11 11:42 UTC, merged